# Generated by Django 3.2.7 on 2022-03-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
